metadata:
  name: ${project.artifactId}-configmap
data:
  application.properties: |-
    spring.datasource.url=jdbc:sqlserver://server.mssql.svc:1433;databaseName=OrdersDB;authentication=SqlPassword;trustServerCertificate=true
    camel.component.kafka.configuration.brokers=dc1-cluster-kafka-bootstrap.streams.svc:9092
    camel.component.infinispan.hosts=infinispan.datagrid.svc
